source 'https://rubygems.org'

ruby '2.7.3'
gem 'padrino'
gem 'puma'
gem 'rake'
gem 'sass'
gem 'sinatra'

# Admin
gem 'activate-admin', github: 'stephenreid321/activate-admin'
gem 'activate-tools', github: 'stephenreid321/activate-tools'
gem 'will_paginate', github: 'mislav/will_paginate'

gem 'airbrake'
gem 'airrecord'
gem 'bcrypt'
gem 'better_html'
gem 'binance'
gem 'chroma'
gem 'delayed_job_mongoid'
gem 'digest-sha3'
gem 'email_address'
gem 'erb_lint', require: false
gem 'eth'
gem 'factory_bot'
gem 'front_matter_parser'
gem 'google_drive'
gem 'htmlbeautifier', github: 'trileuco/htmlbeautifier'
gem 'koala'
gem 'mail'
gem 'mechanize'
gem 'mongoid'
gem 'pocket-ruby'
gem 'redcarpet'
gem 'rss'
gem 'rubocop'
gem 'rubocop-daemon'
gem 'telegram-bot-ruby'
